### PR TITLE
 Updating to allow float based zooms, while retaining support for int based zoom

### PR DESCRIPTION
**Pull request by orionstein**
This allows for calculations involving floats if you pass in a float, while retaining the ability to use the cached results if you pass in an int value.

This is to resolve issue #19

### CODE REVIEW

**Comment by mapsam** [comment]
Howdy @orionstein! Wow, thanks for cranking on this. Before I dive in, would it be possible to provide a new test case for this?

**Comment by orionstein** [comment]
Hi @mapsam, I can do that! Will add a test case sometime in the next couple of days

**Comment by orionstein** [comment]
Added some tests for ll and px

**Comment by mapsam** [comment]
Apologies for the slow response @orionstein - @springmeyer and I have some time set aside early next week for a review. Thanks for your patience!

**Comment by mapsam** [comment]
@orionstein this is looking really great! Thank you for writing up tests. After a review with @flippmoke we just have a couple of requests, specifically around tests (the actual logic holds up 👍)

1. Would you mind adding another test that does some `almostEquals` assertion against a zoom value of `4` versus a zoom value of `4.0000000000001`? This will ensure floats that are _almost_ integers are coming out nearly the same as integer values. I'd say that asserting the outcomes are within six decimals of accuracy would be great.
2. Could you move the constants you've added https://github.com/mapbox/sphericalmercator/pull/32/files#diff-0e001108192afe791f1ed0caacc99b77R101 into the actual tests? This makes the tests a bit more readable, and since we're only using the values in individual tests this will keep values to their units.

Cheers!

**Comment by orionstein** [comment]
@mapsam Thanks for the feedback! Will try to implement those test sometime this week, and will add a note.

Thanks so much!

**Comment by tristen** [comment]
👋 @orionstein any update here? Would love to see this change make it into a release : )

**Comment by mapsam** [comment]
@orionstein @tristen I updated the tests in #34 - going to that and this PR and release 1.1.0!

**Pull request merged**
